media:
  input: src/assets/images
  output: /
  categories:
    - image
content:
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    filename: "{fields.slug}.mdx"
    view:
      fields: [title, slug, date, theme]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: slug
        type: string
        required: true
      - name: createdAt
        label: createdAt
        type: date
        options:
          format: "MMM dd, yyyy"
        required: true
      - name: updatedAt
        label: updatedAt
        type: date
        options:
          format: "MMM dd, yyyy"
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
          max: 5
          collapsible: false
        required: true
      - name: summary
        label: Summary
        type: text
        required: true
      - name: theme
        label: Theme
        type: select
        options:
          values: [tech, info, diary, idea, default]
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true
  - name: talk
    label: Talk
    path: src/content/talk
    type: collection
    filename: "{fields.slug}.mdx"
    view:
      fields: [title, slug, date]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: slug
        type: string
        required: true
      - name: createdAt
        label: createdAt
        type: date
        options:
          format: "MMM dd, yyyy"
        required: true
      - name: updatedAt
        label: updatedAt
        type: date
        options:
          format: "MMM dd, yyyy"
      - name: summary
        label: Summary
        type: text
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
          max: 5
          collapsible: false
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true